# Generated by Django 2.0.7 on 2018-07-31 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='/img/blank-profile.png', upload_to='', verbose_name='Foto de perfil'),
        ),
    ]
