# Generated by Django 2.0.7 on 2018-07-26 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tuite',
            options={'ordering': ('content',)},
        ),
        migrations.RenameField(
            model_name='tuite',
            old_name='coantent',
            new_name='content',
        ),
    ]
