# Generated by Django 2.0.8 on 2018-08-01 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuites', '0003_auto_20180731_1754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tuite',
            options={'ordering': ('-date_created',)},
        ),
    ]
