# Generated by Django 2.0.8 on 2018-08-02 19:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tuites', '0004_auto_20180801_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuite',
            name='liked_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
